// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElCollapse: typeof import("element-plus/es")["ElCollapse"];
    ElCollapseItem: typeof import("element-plus/es")["ElCollapseItem"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    IEpQuestionFilled: typeof import("~icons/ep/question-filled")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VanButton: typeof import("vant/es")["Button"];
    VanImage: typeof import("vant/es")["Image"];
  }
}
