// 功能
// accessibilityHelp
import 'monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp'
// anchorSelect
import 'monaco-editor/esm/vs/editor/contrib/anchorSelect/browser/anchorSelect'
// bracketMatching
import 'monaco-editor/esm/vs/editor/contrib/bracketMatching/browser/bracketMatching'
// browser
import 'monaco-editor/esm/vs/editor/browser/coreCommands'
// caretOperations
import 'monaco-editor/esm/vs/editor/contrib/caretOperations/browser/caretOperations'
import 'monaco-editor/esm/vs/editor/contrib/caretOperations/browser/transpose'
// clipboard
import 'monaco-editor/esm/vs/editor/contrib/clipboard/browser/clipboard'
// codeAction
import 'monaco-editor/esm/vs/editor/contrib/codeAction/browser/codeActionContributions'
// codelens
import 'monaco-editor/esm/vs/editor/contrib/codelens/browser/codelensController'
// colorPicker
import 'monaco-editor/esm/vs/editor/contrib/colorPicker/browser/colorContributions'
// comment
import 'monaco-editor/esm/vs/editor/contrib/comment/browser/comment'
// contextmenu
import 'monaco-editor/esm/vs/editor/contrib/contextmenu/browser/contextmenu'
// cursorUndo
import 'monaco-editor/esm/vs/editor/contrib/cursorUndo/browser/cursorUndo'
// dnd
import 'monaco-editor/esm/vs/editor/contrib/dnd/browser/dnd'
// documentSymbols
import 'monaco-editor/esm/vs/editor/contrib/documentSymbols/browser/documentSymbols'
// find
import 'monaco-editor/esm/vs/editor/contrib/find/browser/findController'
// folding
import 'monaco-editor/esm/vs/editor/contrib/folding/browser/folding'
// fontZoom
import 'monaco-editor/esm/vs/editor/contrib/fontZoom/browser/fontZoom'
// format
import 'monaco-editor/esm/vs/editor/contrib/format/browser/formatActions'
// gotoError
import 'monaco-editor/esm/vs/editor/contrib/gotoError/browser/gotoError'
// gotoLine
import 'monaco-editor/esm/vs/editor/standalone/browser/quickAccess/standaloneGotoLineQuickAccess'
// gotoSymbol
import 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/browser/goToCommands'
import 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition'
// hover
import 'monaco-editor/esm/vs/editor/contrib/hover/browser/hover'
// iPadShowKeyboard
import 'monaco-editor/esm/vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard'
// inPlaceReplace
import 'monaco-editor/esm/vs/editor/contrib/inPlaceReplace/browser/inPlaceReplace'
// indentation
import 'monaco-editor/esm/vs/editor/contrib/indentation/browser/indentation'
// inlayHints
import 'monaco-editor/esm/vs/editor/contrib/inlayHints/browser/inlayHintsContribution'
// inlineCompletions
import 'monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsContribution'
// inspectTokens
import 'monaco-editor/esm/vs/editor/standalone/browser/inspectTokens/inspectTokens'
// lineSelection
import 'monaco-editor/esm/vs/editor/contrib/lineSelection/browser/lineSelection'
// linesOperations
import 'monaco-editor/esm/vs/editor/contrib/linesOperations/browser/linesOperations'
// linkedEditing
import 'monaco-editor/esm/vs/editor/contrib/linkedEditing/browser/linkedEditing'
// links
import 'monaco-editor/esm/vs/editor/contrib/links/browser/links'
// multicursor
import 'monaco-editor/esm/vs/editor/contrib/multicursor/browser/multicursor'
// parameterHints
import 'monaco-editor/esm/vs/editor/contrib/parameterHints/browser/parameterHints'
// quickCommand
import 'monaco-editor/esm/vs/editor/standalone/browser/quickAccess/standaloneCommandsQuickAccess'
// quickHelp
import 'monaco-editor/esm/vs/editor/standalone/browser/quickAccess/standaloneHelpQuickAccess'
// quickOutline
import 'monaco-editor/esm/vs/editor/standalone/browser/quickAccess/standaloneGotoSymbolQuickAccess'
// referenceSearch
import 'monaco-editor/esm/vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch'
// rename
import 'monaco-editor/esm/vs/editor/contrib/rename/browser/rename'
// smartSelect
import 'monaco-editor/esm/vs/editor/contrib/smartSelect/browser/smartSelect'
// snippet
import 'monaco-editor/esm/vs/editor/contrib/snippet/browser/snippetController2'
// suggest
import 'monaco-editor/esm/vs/editor/contrib/suggest/browser/suggestController'
// toggleHighContrast
import 'monaco-editor/esm/vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast'
// toggleTabFocusMode
import 'monaco-editor/esm/vs/editor/contrib/toggleTabFocusMode/browser/toggleTabFocusMode'
// tokenization
import 'monaco-editor/esm/vs/editor/contrib/tokenization/browser/tokenization'
// unicodeHighlighter
import 'monaco-editor/esm/vs/editor/contrib/unicodeHighlighter/browser/unicodeHighlighter'
// unusualLineTerminators
import 'monaco-editor/esm/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators'
// viewportSemanticTokens
import 'monaco-editor/esm/vs/editor/contrib/viewportSemanticTokens/browser/viewportSemanticTokens'
// wordHighlighter
import 'monaco-editor/esm/vs/editor/contrib/wordHighlighter/browser/wordHighlighter'
// wordOperations
import 'monaco-editor/esm/vs/editor/contrib/wordOperations/browser/wordOperations'
// wordPartOperations
import 'monaco-editor/esm/vs/editor/contrib/wordPartOperations/browser/wordPartOperations'
