# Unit Test

name: Unit Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Unit Test (${{ matrix.node-name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
        include:
          - node-version: '16'
            node-name: 'Latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #      - name: Add dev branch
      #        run: git branch dev origin/main

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache ~/.pnpm-store
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-deploy-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-deploy-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-deploy-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint
